feature: Task 4 completed
Gribbirg/todo-list-app pull request #4
Opened 2024-07-13 00:58 UTC by Gribbirg

Четвёртое задание выполнено.

## Сделано по ТЗ

### DI

- Dagger 2
- `Subcomponents` есть в модуле app (по большей части ради галочки)
- `Scope` есть
- Поля я как только не инжектил)
- `ViewModel` "кастыльно" прикручены, главное работает)

<img src="https://renotes.ru/content/public/upload/govnokod_0_o.jpg" width=250px>

- добавлена многомодульность и DI между модулями через зависимости компонентов

### Хранение данных

Сдано в рамках прошлой дз, так что не смотри)

### Gradle

- сделаны таски:
1. проверка размера (отключение - тупо не указание максимального размера)
2. отправка в [телегу](https://t.me/+N7Jfxr_rUvJmMDRi)
3. отправка детализации apk (если не отключено через extension)
- изменено имя apk
- настроен `GitHub Actions`

## Дополнительно

- добавлена сборка `signed` приложения

--------

P.S. 90% изменённых файлов - это тупо их перемещение)

2024-07-15 09:37 UTC, nai1ka reviewed
**DI (5/5)**
✅ Использовать чистый Dagger 2 в своем приложении.
✅ Использовать иерархию Subcomponents и custom Scopes.
✅ Для добавления объектов в Component использовать минимально необходимый способ
✅ Попробовать разбить проект на модули и сделать межмодульный DI с помощью Component Dependencies.

Gradle(4/4)
✅ Вынести конфигурацию сборки проекта в convention плагины.
✅ Повторить плагин, сделанный на практике.
✅ Написать еще одну Gradle Task с названием validateApkSizeFor*
✅ Сделать так, чтобы эта задача всегда запускалась перед задачей выгрузки apk файла
✅ Выходными данными задачи должна быть информация о размере apk файла
✅ Сделать extension для плагина, который позволит отключать задачу проверки размера файла и задавать границу этого размера. Тот самый N мб.
✅ Поменять название у отправляемого apk файла. 
✅ Настроить Github Actions для сборки проекта и выгрузки apk файла в телеграм на каждый ПР и линковки apk файла к CI сборке.



Очень много всего сделал, классная работа)
@nai1ka

2024-07-15 09:37 UTC, nai1ka commented on app/src/main/java/ru/gribbirg/todoapp/di/modules/ListFeatureModule.kt
> +            ListFeatureFactory(depsImpl)
Как будто здесь можно было обойтись просто @Inject в конструкторе

2024-07-15 09:37 UTC, nai1ka commented on app/src/main/java/ru/gribbirg/todoapp/navigation/NavGraph.kt
> +        appComponent.listFeatureComponent().listViewModel()
Лучше переделать как в гайде. Не уверен, что это надежный способ

2024-07-15 09:49 UTC, Gribbirg commented on app/src/main/java/ru/gribbirg/todoapp/di/modules/ListFeatureModule.kt
> +            ListFeatureFactory(depsImpl)
Суть подхода как у меня в том, чтобы сделать модули независимыми друг от друга в плане DI. Т.е. Если из `ListFeature` DI уйдёт или переедет с `Dagger`а, то при этом не придётся менять остальные модули. Если делать через `@Inject`, то при изменении DI у `ListFeature` придётся менять и все модули, где он использовался, т.к. `@Inject`а может уже не быть(

2024-07-15 12:40 UTC, Zakis0 requested changes
DI: 5/5
Gradle: 4/4

Крутая работа!

2024-07-15 12:40 UTC, Zakis0 commented on build-logic/src/main/kotlin/ru/gribbirg/todoapp/tasks/SizeCheckTask.kt
> +                "Apk is too large!\nName: ${file.name}\nSize: $size KB\nMax size: $maxSizeKb KB"
KB можно вынести в константы. Можно забыть где-то поменять, если решишь отображать размер, например, в МБ

2024-07-15 12:40 UTC, Zakis0 commented on build-logic/src/main/kotlin/ru/gribbirg/todoapp/tasks/SizeCheckTask.kt
> +        val size = file.length() / 1024
1024 - магическое число

2024-07-15 17:20 UTC, merged

2024-07-17 10:51 UTC, Uncreated reviewed
В целом все ок)

2024-07-17 10:51 UTC, Uncreated commented on app/src/main/java/ru/gribbirg/todoapp/TodoApplication.kt
> +    internal val appComponent by lazy {
Можно lazy(NONE), т.к. не нужна синхронизация на мейн треде

2024-07-17 10:51 UTC, Uncreated commented on app/src/main/java/ru/gribbirg/todoapp/navigation/NavGraph.kt
> +        appComponent.editFeatureComponent().editFeatureFactory().createViewModelFactory()
Пустая строка

2024-07-17 10:51 UTC, Uncreated commented on app/src/main/java/ru/gribbirg/todoapp/navigation/NavGraph.kt
> +            ru.gribbirg.list.TodoListItemScreen(
Лучше импортнуть и не писать весь путь

2024-07-17 10:51 UTC, Uncreated commented on app/src/main/java/ru/gribbirg/todoapp/navigation/NavGraph.kt
> +                },
Запятые, конечно, хорошо, если есть понимание зачем они пишутся в конце)

2024-07-17 10:51 UTC, Uncreated commented on feature/list/src/main/java/ru/gribbirg/list/di/ListFeatureFactory.kt
> +class ListFeatureFactory(deps: ListFeatureDependencies) {
Класс лишний, можно все тоже самое сделать напрямую. `ListFeatureDependencies` можно получать напрямую из AppComponent как зависимость. Сам класс зависимостей должен храниться в модуле рядом с компонентом `ListFeatureComponent`, т.о. все равно кто будет реализовывать эти зависимости